language: python
python:
- '3.4'
addons:
  postgresql: "9.4"
services:
  - postgresql
branches:
  only:
  - master
install:
- pip install -r requirements.txt
- pip install pep8
script:
- nosetests -v --with-coverage --cover-html --cover-inclusive
- pep8 batoru --ignore=E501
after_success:
- ./update-gh-pages.sh
env:
  global:
    secure: W05bj3VlxXHFohmo7G9z968MDO66uvITlbxFsDoajAWp8xstxnt3aGMDn2GUUB+nNwY4qkuE/mg0ixd8n1xi3/7Q9+Z4zFk69yMqbrQ5GlAzigNS59nPahJ+pclMgjMoTbdkh4MAQ/eG+VqbFBq1cgUlt+TdJnPAwNtanBPe+1CNVC2AfH45wuHvmipYR5hDW2MySidUFW4T1225rfjJo2lyu+MJhNJLA/7k3idRQlOsUFi34T58MtfV2+r8PKr8q8vZl3wDt3elqdq29M3lVgV24of/1FEOd4AtpTO3Oc6MDzEsYwmtbQJM++P9/NSOlpDlhFbKuoHIfdGqT/ITMwhmdixadpu/FkV5CdEKxZPPkv8J+2OTnk5D3idM3mF/y4MP/OuxWtjarOUVjiXw15zrV2HEfxYY/HE4Fth6wSog2BASEbZXSgkxhahbRzC1vHanC4y26amXChW/JmXFXGLuHenLLKkXiuWTM6vU6k3/ofjTY4issqWgiLg98egFVhudaWkrKcNtyj1rPcoMBPU3M16Cdt38r409LWhO9HpNsEQz19PI0U+m2sxEnwQ0sU2EASU1k4JcCB63V1rEYJhEFHBRoZWaVyARp8/YcIUTeGzqLiDWSM5CNkbYY8Vq5oZnOk6HBhjffEDHjto0dNcER6HruREIHYpx+vYrfYE=
deploy:
  provider: heroku
  api_key:
    secure: d3BSdxJpwJ96ZVZh+g4m7GFr6kL5YXjofNuOd1OFLKEntpIQ/UR4+qiNVwisJ50pygzYeWei/mSmdsNbCU9A9Dr8GSER5+haDVgcdatELVRhln/rLCuJTzOmhtsTqjWIOTlMUMX8n/46GjXm2QMMmXOFxWPKu77F7iFNg7ViZfUGj2C/kihs8fSqyeavw5Gdhg2bFA1vX4UUpl+3/6IzChaO1wIJCHwSkJAdhJk9YbhoVtNQHypB9arUulm2DTqeng59nxvXofnaOq0T04mDxTw8+ZElH2mAkLqlVh788H5WBK/qDjdg2kfTnVLoP1GeLzCiDC2MB0Cu5saNkOeZmOelYGyI1XTWsCU/U8QW7z6hnEw2amsF5nr2ADiodmZU2WXGoYKFHzM07Nw3zQoaXh7FIfSoS/ETiqOBuTU4V1RCgb5SoKmotlZdBfS6M/N7jB3Gr3ish0XVFXu+KUz3SIiONdT9z6HIHrbDlCX2caQpCni4v3AQoAoLVy5AVhWJNEJV2pnUSoMrbpQJRPALIQHnfjHjilTIdymyEGOGZk5AihPZlV3ocptQ3T/y7BmudUUWSfCpD6KCkybglojJbjAznYZBtm2q7m+pBIkoRTVOcAzKyi2ZWfIbYkz1MJyWZnMMLn8pp7ixoRhQZsBseOEL9yCL5MPkqdl1M6cKdVU=
  app: intense-anchorage-9323
