version: '2'
services:
  batoru-redis:
    image: redis
    ports:
     - "6379:6379"
  batoru-rabbitmq:
    image: rabbitmq
    ports:
     - "5672:5672"
  batoru-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: batoru-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  batoru-royale-client:
    image: ishino/batoru-royale
    command: python client.py
    ports:
     - "5000:5000"
    links:
     - batoru-redis
     - batoru-rabbitmq
     - batoru-elasticsearch
    depends_on:
     - batoru-redis
     - batoru-rabbitmq
     - batoru-elasticsearch

  batoru-royale-read:
    image: ishino/batoru-royale
    command: python read.py
    links:
     - batoru-redis
     - batoru-rabbitmq
     - batoru-elasticsearch
    depends_on:
     - batoru-redis
     - batoru-rabbitmq
     - batoru-elasticsearch

volumes:
  esdata1:
    driver: local
